document:

  title: Web-Dev-For-Beginners

  original:
    url: https://github.com/Azure/azure-sdk.git
    branch: main

  translated:
    url: https://github.com/Azure/azure-sdk-korean.git
    translated-branch: main