document:

  title: Web-Dev-For-Beginners

  translate-by: dir

  original:
    url: https://github.com/microsoft/Web-Dev-For-Beginners.git
    branch: main

  translated:
    url: https://github.com/Azure/azure-sdk-korean.git
    translated-branch: main

keys:
  translate-api: update-api-at-github-action-secret