# This is a basic workflow to help you get started with Actions

name: diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ docsify ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
         python-version: ${{ matrix.python-version }}
    
       # remote

      - name: remote upstream
        run : |
             git remote add upstream https://github.com/Azure/azure-sdk-korean.git
             git remote -v
            
      # checkout
      - name : git checkout
        run : git checkout -b upstream/main
                      
      # fetch
      - name : fetch upstream
        run : git fetch upstream

              
      # 최신 id               
      - name : main id
        id : main
        run : echo ::set-output name=main_id::$(git rev-parse upstream/main)

      # 이전 id
      - name : upstream id
        id : vars
        run : |

              echo ::set-output name=upstream_id::$(git rev-parse refs/remotes/upstream/main^)
      
      # id 출력
      - name : output 
        run : |
              echo ${{steps.main.outputs.main_id}}
              echo ${{steps.vars.outputs.upstream_id}}

      # git diff
      - name: Run diff.py
        run: python diff.py ${{steps.vars.outputs.upstream_id}} ${{steps.main.outputs.main_id}}

      
#      - name : git 
#        run : |
#                git config --global user.email "gaga2353@gmail.com"
#                git config --global user.name "bmlsj"
       

#      - name : commit
#        run : |
#              git pull origin main --rebase  
#              git add .
#              git commit -m "commit index.md"
#              git push --set-upstream origin upstream/main

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
            author_name: bmlsj
            author_email: gaga2353@gmail.com
            message: 'Your commit message'
            add: 'contact/index.md'
            pull: '--rebase --autostash ...'

