# This is a basic workflow to help you get started with Actions

name: diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
     branches: [ main ]    
     
  schedule:
     - cron: '0 0 * * 3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./Web-Dev-For-Beginners

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        
      - name: jinja2 install
        run : pip install jinja2
        
      - name: checkout to result branch
        run : |
              git remote update
              git fetch
              git checkout pl
              git branch -a
        
      - name: source file copy
        run : |
              git checkout remotes/origin/diff_script ./scripts
              git reset HEAD ./scripts
         
      - name: cloning repository
        run : git clone https://github.com/devrel-kr/Web-Dev-For-Beginners.git
          
      - name: add upstream
        run : git remote add upstream https://github.com/microsoft/Web-Dev-For-Beginners.git
        working-directory: ${{ env.working-directory }}
      
      - name: check repository
        run : git remote -v
        working-directory: ${{ env.working-directory }}

      - name: fetch upstream
        run : git fetch upstream
        working-directory: ${{ env.working-directory }}
        
      - name: checkout to upstream
        run : git checkout upstream/main
        working-directory: ${{ env.working-directory }}
        
      - name: copy python script
        run : |
              cp scripts/* ${{ env.working-directory }}
        
      - name: run python script
        run : python git_diff.py main upstream/main ../_posts/$(date --rfc-3339=date)-title.md
        working-directory: ${{ env.working-directory }}
        
      - name: Set config
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run : |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
        
      - name: push to github
        run : |
          git add _posts/*.md
          git commit -m "Add report file"
          
      - name: Push to pl branch
        run: git push origin pl --force

